export interface VerificationEvidence {
  passed: boolean;
  astInvariantsValid: boolean;
  testExitCode: number;
  scopeViolations: string[];
  executionTimeMs: number;
  receiptSha256: string;
}

export function formatEvidenceComment(evidence: VerificationEvidence): string {
  const badge = evidence.passed ? "🛡️ **PROOF-CARRYING VERIFICATION PASSED**" : "🚨 **VERIFICATION REJECTED**";
  return `### ${badge}

> This Pull Request has been verified by the [LetItLoop Deterministic Engine](https://github.com/sdageltc/letitloop).

| Verification Check | Status | Empirical Details |
|---|:---:|---|
| **AST Invariant Integrity** | ${evidence.astInvariantsValid ? "🟢 PASS" : "🔴 FAIL"} | Zero signature or parameter drift |
| **Test Suite Execution** | ${evidence.testExitCode === 0 ? "🟢 PASS" : "🔴 FAIL"} | Process Exit Code: \`${evidence.testExitCode}\` |
| **Scope Fencing & Mutation Lease** | ${evidence.scopeViolations.length === 0 ? "🟢 PASS" : "🔴 FAIL"} | ${evidence.scopeViolations.length} undeclared file mutations |

\`\`\`json
{
  "proof_receipt": "${evidence.receiptSha256}",
  "engine_latency_ms": ${evidence.executionTimeMs},
  "deterministic_gates": "${evidence.passed ? "PASS" : "FAIL"}"
}
\`\`\`
*Generated by \`letitloop-action@v1\`.*`;
}
